@rem Builds the Test Binaries

tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-nop-1.bin flame32-libs\unit-tests\test-nop-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-lod-1.bin flame32-libs\unit-tests\test-lod-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ldl-1.bin flame32-libs\unit-tests\test-ldl-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-mov-1.bin flame32-libs\unit-tests\test-mov-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-swp-1.bin flame32-libs\unit-tests\test-swp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ldm-1.bin flame32-libs\unit-tests\test-ldm-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-sto-1.bin flame32-libs\unit-tests\test-sto-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-inc-1.bin flame32-libs\unit-tests\test-inc-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-dec-1.bin flame32-libs\unit-tests\test-dec-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-add-1.bin flame32-libs\unit-tests\test-add-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-sub-1.bin flame32-libs\unit-tests\test-sub-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-mul-1.bin flame32-libs\unit-tests\test-mul-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-div-1.bin flame32-libs\unit-tests\test-div-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-mod-1.bin flame32-libs\unit-tests\test-mod-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-mls-1.bin flame32-libs\unit-tests\test-mls-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-dvs-1.bin flame32-libs\unit-tests\test-dvs-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-mds-1.bin flame32-libs\unit-tests\test-mds-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-shl-1.bin flame32-libs\unit-tests\test-shl-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-shr-1.bin flame32-libs\unit-tests\test-shr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-sli-1.bin flame32-libs\unit-tests\test-sli-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-sri-1.bin flame32-libs\unit-tests\test-sri-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-rtl-1.bin flame32-libs\unit-tests\test-rtl-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-rtr-1.bin flame32-libs\unit-tests\test-rtr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-rli-1.bin flame32-libs\unit-tests\test-rli-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-rri-1.bin flame32-libs\unit-tests\test-rri-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bor-1.bin flame32-libs\unit-tests\test-bor-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-and-1.bin flame32-libs\unit-tests\test-and-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-xor-1.bin flame32-libs\unit-tests\test-xor-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bst-1.bin flame32-libs\unit-tests\test-bst-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-brs-1.bin flame32-libs\unit-tests\test-brs-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bcp-1.bin flame32-libs\unit-tests\test-bcp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-cmp-1.bin flame32-libs\unit-tests\test-cmp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-cpz-1.bin flame32-libs\unit-tests\test-cpz-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-cpi-1.bin flame32-libs\unit-tests\test-cpi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-jpr-1.bin flame32-libs\unit-tests\test-jpr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-jmp-1.bin flame32-libs\unit-tests\test-jmp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-jpc-1.bin flame32-libs\unit-tests\test-jpc-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-clr-1.bin flame32-libs\unit-tests\test-clr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-cal-1.bin flame32-libs\unit-tests\test-cal-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-clc-1.bin flame32-libs\unit-tests\test-clc-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-inp-1.bin flame32-libs\unit-tests\test-inp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-out-1.bin flame32-libs\unit-tests\test-out-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-inr-1.bin flame32-libs\unit-tests\test-inr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-otr-1.bin flame32-libs\unit-tests\test-otr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-psh-1.bin flame32-libs\unit-tests\test-psh-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-pop-1.bin flame32-libs\unit-tests\test-pop-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-psi-1.bin flame32-libs\unit-tests\test-psi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-hlt-1.bin flame32-libs\unit-tests\test-hlt-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ppp-1.bin flame32-libs\unit-tests\test-ppp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ret-1.bin flame32-libs\unit-tests\test-ret-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-lmr-1.bin flame32-libs\unit-tests\test-lmr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-str-1.bin flame32-libs\unit-tests\test-str-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-blod-1.bin flame32-libs\unit-tests\test-blod-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bldm-1.bin flame32-libs\unit-tests\test-bldm-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bsto-1.bin flame32-libs\unit-tests\test-bsto-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-binp-1.bin flame32-libs\unit-tests\test-binp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bout-1.bin flame32-libs\unit-tests\test-bout-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-binr-1.bin flame32-libs\unit-tests\test-binr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-botr-1.bin flame32-libs\unit-tests\test-botr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bpsh-1.bin flame32-libs\unit-tests\test-bpsh-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bpop-1.bin flame32-libs\unit-tests\test-bpop-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bpsi-1.bin flame32-libs\unit-tests\test-bpsi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bppp-1.bin flame32-libs\unit-tests\test-bppp-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-blmr-1.bin flame32-libs\unit-tests\test-blmr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-bstr-1.bin flame32-libs\unit-tests\test-bstr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-kic-1.bin flame32-libs\unit-tests\test-kic-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-kir-1.bin flame32-libs\unit-tests\test-kir-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-krt-1.bin flame32-libs\unit-tests\test-krt-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-kei-1.bin flame32-libs\unit-tests\test-kei-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-kdi-1.bin flame32-libs\unit-tests\test-kdi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ksi-1.bin flame32-libs\unit-tests\test-ksi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ehr-1.bin flame32-libs\unit-tests\test-ehr-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ssi-1.bin flame32-libs\unit-tests\test-ssi-1.asm
tools\customasm\customasm.exe -f binary -o flame32-libs\unit-tests\test-ert-1.bin flame32-libs\unit-tests\test-ert-1.asm
